config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.contrib.staticfiles.urls import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('travel_planning.urls')),
    path('accounts/', include('allauth.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

travel_planning/urls.py
from django.urls import path
from . import views

app_name = 'travel_planning'
urlpatterns = [
    # path('',views.MapView.as_view(), name='map'),
    path('', views.IndexView.as_view(), name='index'),
    path('automap/',views.AutomapView.as_view(), name='automap'),
    path('automap/<int:pk>/',views.MyPlanUpdateView.as_view(), name='plan-update'),
    # path('test/', views.TestView.as_view(), name='test')
    path('share/detail/<int:pk>/', views.SharePlanView.as_view(), name='share'),
    
    path('share/plan-list', views.PlanListView.as_view(), name='list'),
    path('share/success', views.ShareSuccessView.as_view(), name='success'),
    path('share/canceled', views.ShareCanceledView.as_view(), name='canceled'),
    
    path('my-plan-list', views.MyPlanListView.as_view(), name='mylist'),
    path('plan-detail/<int:pk>', views.MyPlanDetailView.as_view(), name='mydetail'),
    path('plan-delete/<int:pk>', views.MyPlanDeleteView.as_view(), name='mydelete'),

    #コピーのURL
    path('map_copy/<int:pk>/',views.PlanCopyView.as_view(), name='plan-copy'),
]

travel_planning/models.py
from django.db import models
from accounts.models import CustomUser

import os
import time
from datetime import datetime

#旅行計画モデル
class Plan(models.Model):
    user = models.ForeignKey(CustomUser, verbose_name='ユーザー', on_delete=models.PROTECT)
    prefectural_names = models.TextField(verbose_name='県名') #例：'千葉県,東京都'
    photo = models.ImageField(verbose_name='メイン画像', blank=True, null=True)
    detail = models.TextField(verbose_name='詳細')
    plan = models.TextField(verbose_name='旅行計画') #例：'牛久大仏,ChIJ4-9ANlRuImARS4u9SEpdN8I,986,60;浄土宗 佛法山 東漸寺,ChIJeakrKlKbGGAR3PKsg0N6oFQ,1110,60;'、splitで展開
    sub_details = models.TextField(verbose_name='サブ詳細一覧') #例：'詳細1;詳細2;'
    created_at = models.DateTimeField(verbose_name='作成日時', max_length=10, auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name='更新日時', max_length=10, auto_now=True, blank=True, null=True)
    is_deleted = models.BooleanField(verbose_name='削除フラグ', default=False)
    is_action = models.BooleanField(verbose_name='公開フラグ', default=False)

    class Meta:
        verbose_name_plural = 'Plan'
    
    def __str__(self):
        string = self.plan.split(",")
        return string[0] #例：20代男性
    
    def ago(self):
        dt_now = time.time() #現在時刻
        dt_updated = self.updated_at.timestamp() #更新日の取得
        
        diff = dt_now - dt_updated #差分
        
        d = datetime.utcfromtimestamp(diff)
        
        if d.year - 1970:
            return str(d.year - 1970) + "年前"
        elif d.month - 1:
            return str(d.month - 1) + "ヵ月前"
        elif d.day - 1:
            return str(d.day) + "日前"
        elif d.hour:
            return str(d.hour) + "時間前"
        elif d.minute:
            return str(d.minute) + "分前"
        else:
            return "数秒前"

#いいねモデル（未使用）
class Like(models.Model):
    user = models.ForeignKey(CustomUser, verbose_name='ユーザー', on_delete=models.PROTECT)
    plan = models.ForeignKey(Plan, verbose_name='旅行計画', on_delete=models.PROTECT)

    class Meta:
        verbose_name_plural = 'Like'
    
    def __str__(self):
        return self.user.username #仮です！

travel_planning/forms.py
from django import forms
from .models import Plan

class MyPlanCreateForm(forms.ModelForm):
    class Meta:
        model = Plan
        fields = ('prefectural_names','plan')
        def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)


class MyPlanUpdateForm(forms.ModelForm):
    class Meta:
        model = Plan
        fields = ('prefectural_names','plan')
        def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)

travel_planning/views.py
from django.shortcuts import render
from django.views import generic
from django.contrib import messages

from .forms import MyPlanUpdateForm, MyPlanCreateForm
from django.urls import reverse_lazy

from .models import *
from django.contrib.auth.mixins import LoginRequiredMixin

from config import settings
import os

# Create your views here.
class IndexView(generic.TemplateView):
    template_name = "index.html"
    
class AutomapView(generic.CreateView):
    template_name = 'auto.html'
    model = Plan
    form_class = MyPlanCreateForm

    def post(self, request, *args, **kwargs):
        try:
            plan = Plan(user=request.user, prefectural_names=request.POST["prefectural_names"], plan=request.POST["plan"])
            plan.save()

            messages.success(request, '計画を保存しました。')
        except:
            messages.error(request, 'エラーが起きたようです。')
        return render(request, 'auto.html')


class TestView(generic.TemplateView):
    template_name = "test.html"

class PlanListView(generic.ListView):
    model = Plan
    template_name = "plan_list.html"

    def get_queryset(self):
        plans = Plan.objects.filter(prefectural_names__contains='北海道').filter(is_action=True).order_by('-created_at')
        return plans

    def post(self, request, *args, **kwargs):
        plans = Plan.objects.filter(prefectural_names__contains=request.POST['prefs']).filter(is_action=True).order_by('-created_at')
        context = {
            'prefsValue' : request.POST['prefs'],
            'plan_list' : plans
        }
        return render(request, 'plan_list.html', context)

class SharePlanView(LoginRequiredMixin, generic.DetailView):
    # 問題点：自分が他人の計画を投稿できてしまう
    model = Plan
    template_name = "shiozaki/share_plan.html"

    def __init__(self, *args, **kwargs):
        print(args)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        plan = Plan.objects.get(id=self.kwargs['pk']).plan
        subD = Plan.objects.get(id=self.kwargs['pk']).sub_details
        detailList = subD.split(';')

        perPlace = plan.split(';')
        planList = []

        for i in range(len(perPlace)):
            place = perPlace[i].split(",")
            place.append(detailList[i] if i < len(detailList) else '')
            planList.append(place)
        
        context = {
            'object' : Plan.objects.get(id=self.kwargs['pk']),
            'planList' : planList,
        }
        return context

class ShareSuccessView(generic.TemplateView):
    def post(self, request, *args, **kwargs):
        context = {
            'mainPhoto': request.FILES['メイン画像'],
            'mainDescription': request.POST['詳細'],
            'subDescription': request.POST.getlist('サブ詳細'),
        }
        subDes = ''
        for index in range(len(context['subDescription'])):
            subDes += context['subDescription'][index]
            if index != (len(context['subDescription'])-1):
                subDes += ';'

        os.chdir(os.getcwd() + settings.MEDIA_URL)

        file_obj = request.FILES.get("メイン画像")
        f1=open(file_obj.name,"wb")

        for i in file_obj.chunks():
            f1.write(i)

        f1.close()

        os.chdir('..')

        Plan.objects.filter(id=request.POST['ID']).update(
            photo=context['mainPhoto'],
            detail=context['mainDescription'], 
            sub_details=subDes, is_action=True
        )
        return render(request, 'shiozaki/share_success.html')

class ShareCanceledView(generic.TemplateView):
    #共有取り消しビュー（塩﨑）
    def post(self, request, *args, **kwargs):
        Plan.objects.filter(id=request.POST['ID']).update(
            is_action=False
        )
        return render(request, 'shiozaki/share_canceled.html')


class MyPlanListView(generic.ListView):
    model = Plan
    template_name = "my_plan_list.html"

    def get_queryset(self):
        plans = Plan.objects.filter(user=self.request.user).order_by('-created_at')
        return plans
    
    def post(self, request, *args, **kwargs):
        try:
            plan = Plan(user=request.user, prefectural_names=request.POST["prefectural_names"], plan=request.POST["plan"])
            plan.save()

            messages.success(request, '計画を保存しました。')
        except:
            messages.error(request, 'エラーが起きたようです。')

        return render(request, 'my_plan_list.html')

class MyPlanDetailView(generic.DetailView):
    model = Plan
    template_name = "shiozaki/plan_detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        
        user = Plan.objects.get(id=self.kwargs['pk']).user
        plan = Plan.objects.get(id=self.kwargs['pk']).plan
        subD = Plan.objects.get(id=self.kwargs['pk']).sub_details
        detailList = subD.split(';')

        perPlace = plan.split(';')
        planList = []

        for i in range(len(perPlace)):
            place = perPlace[i].split(",")
            place.append(detailList[i] if i < len(detailList) else '')
            planList.append(place)
        
        context = {
            'object' : Plan.objects.get(id=self.kwargs['pk']),
            'planOwner' : user,
            'planList' : planList
        }
        return context

class MyPlanUpdateView(LoginRequiredMixin, generic.UpdateView):
    #問題点：他人の計画を編集できてしまう
    """
    注意！
    仕様のため、保存ボタンを押さないとエラーが起きません！
    """
    model = Plan
    template_name = 'auto.html'
    form_class = MyPlanUpdateForm

    def get_success_url(self):
        return reverse_lazy('travel_planning:mydetail', kwargs={'pk': self.kwargs['pk']})
    def form_valid(self, form):
        if Plan.objects.get(id=self.kwargs['pk']).user == self.request.user:
            messages.success(self.request, '更新しました。')
            return super().form_valid(form)
        else:
            messages.error(self.request, "更新に失敗しました。")
            return super().form_invalid(form)

    def form_invalid(self, form):
        messages.error(self.request, "更新に失敗しました。")
        return super().form_invalid(form)
#追加コード（塩崎）
class MyPlanDeleteView(LoginRequiredMixin, generic.DeleteView):
    #削除ビュー
    model = Plan
    template_name = 'shiozaki/share_delete.html'
    success_url = reverse_lazy('travel_planning:mylist')

    def delete(self, request, *args, **kwargs):
        #削除フラグ使う・・・？
        messages.success(self.request, "計画を削除しました。")
        return super().delete(request, *args, **kwargs)

class PlanCopyView(LoginRequiredMixin, generic.CreateView):
    #コピーに使うビュー
    #問題点：自分の計画をコピーできてしまう（多分）
    model = Plan
    template_name = 'auto.html'
    form_class = MyPlanCreateForm

    def get_context_data(self, **kwargs):
        try:
            if Plan.objects.get(id=self.kwargs['pk']).user == self.request.user:
                messages.error(self.request, "エラーが起こりました。")

                return {}
            else:
                #URLにあるPKから計画一覧を取得
                plan = Plan.objects.get(id=self.kwargs['pk']).plan

                context = {
                    'copiedPlan' : plan
                }
                return context
        except self.model.DoesNotExist:
            messages.error(self.request, "エラーが起こりました。")
            return {}

travel_planning/templates/shiozaki/plan_detail.html
{% extends "../base.html" %}

{% load i18n %}

{% block head_title %}旅行計画{% endblock %}

{% block content %}

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/planDetail.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/memoSpaceSmall.css' %}">

<div id="contents">

    <h1>旅行計画</h1>

    <div class="space_1x1">
        <section>
            <h2>
                {% if object %}
                {{ object }}
                {% else %}
                タイトルなし
                {% endif %}
            </h2>
            <div id="imageSpace">
                {% if object.photo %}
                <img src="{{ object.photo.url }}" id="mainPhotoDisplay">
                {% else %}
                <img src="{% static 'images.png' %}" id="mainPhotoDisplay">
                {% endif %}
            </div>
            <br>
            <div id="mainDescription">{{ object.detail }}</div>
        </section>
    </div>

    <div class="space_1x1">
        <h3>スケジュール</h3>
        <div id="memo" class="memo">
            <div id="memoSpace">
                <div class="schedule_table">
                    ここはスケジュールカードが入る欄
                </div>
            </div>
        </div>
        {% for plan in planList %}
        {% if plan.2 != "NaN" %}
        <input type="hidden" name="scheduleName" value="{{ plan.0 }}">
        <input type="hidden" name="scheduleBeginTime" value="{{ plan.2 }}">
        <input type="hidden" name="scheduleStayTime" value="{{ plan.3 }}">
        {% endif %}
        {% endfor %}
    </div>

    <div class="space_1x2">
        {% for plan in planList %}
        {% load mathfilters %}
        <table>
            <tr>
                <td id="Timeline_Span">
                    <div class="dot">
                        {% if forloop.counter > 1 %}
                        <div class="numberLine" style="top: -203px; height: 203px;"></div>
                        {% endif %}
                    </div>
                </td>
                <td id="Timeline_TimePlace" class="timeDisplay">
                    {% if plan.2 != "NaN" %}
                    {{ plan.2|div:60|sub:0.5|floatformat:0 }}:{% if plan.2|mod:60 < 10 %}0{% endif %}{{ plan.2|mod:60 }}
                        {% else %} --:-- {% endif %} </td>
                <td rowspan="3" id="Timeline_Photo">
                    <div id="schedulePhotoSpace">
                        <img src="" alt="">
                    </div>
                </td>
            </tr>
            <tr>
                <td rowspan="2" id="Timeline_Span">
                </td>
                <td id="Timeline_TimePlace">
                    {{ plan.0 }}
                </td>
            </tr>
            <tr>
                <td id="Timeline_TimePlace">
                    <div id="descriptionSpace">{{ plan.4 }}</div>
                </td>
            </tr>
        </table>
        {% endfor %}
        <table>
            <tr>
                <td id="Timeline_Span">
                    <div class="dot">
                        <div class="numberLine" style="top: -203px; height: 203px;"></div>
                    </div>
                </td>
                <td id="Timeline_TimePlace" class="timeDisplay">
                    FINISH
                </td>
                <td id="Timeline_Photo">

                </td>
            </tr>
        </table>
    </div>

    <div class="space_1x2">
        <br>
        <form action="{% url 'travel_planning:canceled' %}" method="POST">
            {% csrf_token %}
            <div class="d-flex">
                <a class="btn btn-outline-primary me-auto" href="{% url 'travel_planning:list' %}">戻る</a>


                {% if user == planOwner %}
                {% if object.is_action %}
                <input type="hidden" name="ID" value="{{ object.pk }}">
                <input class="btn btn-outline-warning" type="submit" value="投稿を取り消す">
                {% endif %}
                <a class="btn btn-outline-danger" href="{% url 'travel_planning:mydelete' object.pk %}">削除</a>
                {% elif user.is_authenticated %}
                <a class="btn btn-outline-warning" href="{% url 'travel_planning:plan-copy' object.pk %}">コピー</a>
                {% endif %}
            </div>
    </div>
    </form>
    <br>
</div>
</div>

<script src="{% static 'js/memoSpaceSmall.js' %}"></script>

{% endblock %}

travel_planning/templates/shiozaki/share_canceled.html
{% extends "../base.html" %}

{% load i18n %}

{% block head_title %}投稿取り消し{% endblock %}

{% block content %}

{% load static %}
<style>
    h2 {
        text-align: center;
        padding: 14px 0;
    }

    a {
        width: 100px;
        margin: 0 auto;
        text-align: center;
        padding-bottom: 100px;
    }

    #main {
        text-align: center;
    }
</style>

<h2>投稿を取り消しました。</h2>

<a class="btn btn-outline-primary" href="{% url 'travel_planning:mylist' %}">OK</a>

<br>

{% endblock %}

travel_planning/templates/shiozaki/share_delete.html
{% extends "../base.html" %}

{% load i18n %}

{% block head_title %}削除しますか？{% endblock %}

{% block content %}

{% load static %}
<style>
    h2 {
        text-align: center;
        padding: 14px 0;
    }

    #buttons button,
    #buttons a {
        width: 106px;
    }
    #buttons {
        width: 230px;
        margin: 0 auto;
        padding-bottom: 100px;
    }
</style>

<form method="post">
    {% csrf_token %}
    <h2>本当に削除しますか？</h2>
    <div id="buttons">
        <button class="btn btn-outline-danger">削除</button>
        <a class="btn btn-outline-primary" href="{% url 'travel_planning:mylist' %}">キャンセル</a>
    </div>
</form>

{% endblock %}

travel_planning/templates/shiozaki/share_plan.html
{% extends "../base.html" %}

{% load i18n %}

{% block head_title %}旅行計画投稿{% endblock %}

{% block content %}

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/sharePlan.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/memoSpaceSmall.css' %}">

<div id="contents">

    <h1>旅行計画投稿</h1>

    <form action="{% url 'travel_planning:success' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}

        <input type="hidden" name="ID" value="{{ object.pk }}">

        <div class="space_1x1">
            <section>
                <h2>
                    {% if object %}
                    {{ object }}
                    {% else %}
                    タイトルなし
                    {% endif %}
                </h2>
                <input type="file" onchange="OnFileSelect(this);" name="メイン画像" id="mainPhoto" required><br>
                <div id="imageSpace">
                    <img src="" alt="" id="mainPhotoDisplay">
                </div>
                <br>
                <textarea name="詳細" id="mainDescription" placeholder="32字以内で詳細を入力" maxlength="32" required>{{ object.detail }}</textarea>
            </section>
        </div>

        <div class="space_1x1">
            <h3>スケジュール</h3>
            <div id="memo" class="memo">
                <div id="memoSpace">
                    <div class="schedule_table">
                        ここはスケジュールカードが入る欄
                    </div>
                </div>
            </div>
            {% for plan in planList %}
            {% if plan.2 != "NaN" %}
            <input type="hidden" name="scheduleName" value="{{ plan.0 }}">
            <input type="hidden" name="scheduleBeginTime" value="{{ plan.2 }}">
            <input type="hidden" name="scheduleStayTime" value="{{ plan.3 }}">
            {% endif %}
            {% endfor %}
        </div>

        <div class="space_1x2">
            {% for plan in planList %}
            {% load mathfilters %}
            <table>
                <tr>
                    <td id="Timeline_Span">
                        <div class="dot">
                            {% if forloop.counter > 1 %}
                            <div class="numberLine" style="top: -210px; height: 210px;"></div>
                            {% endif %}
                        </div>
                    </td>
                    <td id="Timeline_TimePlace" class="timeDisplay">
                        {% if plan.2 != "NaN" %}
                        {{ plan.2|div:60|sub:0.5|floatformat:0 }}:{% if plan.2|mod:60 < 10 %}0{% endif %}{{ plan.2|mod:60 }}
                        {% else %}
                        --:--
                        {% endif %}
                    </td>
                    <td rowspan="3" id="Timeline_Photo">
                        <div id="schedulePhotoSpace">
                            <img src="" alt="">
                        </div>
                    </td>
                </tr>
                <tr>
                    <td rowspan="2" id="Timeline_Span">
                        
                    </td>
                    <td id="Timeline_TimePlace">
                        {{ plan.0 }}
                    </td>
                </tr>
                <tr>
                    <td id="Timeline_TimePlace">
                        <textarea name="サブ詳細" cols="30" rows="20" placeholder="128字以内で詳細を入力" maxlength="128" required>{{ plan.4 }}</textarea>
                    </td>
                </tr>
            </table>
            {% endfor %}
            <table>
                <tr>
                    <td id="Timeline_Span">
                        <div class="dot">
                            <div class="numberLine" style="top: -210px; height: 210px;"></div>
                        </div>
                    </td>
                    <td id="Timeline_TimePlace" class="timeDisplay">
                        FINISH
                    </td>
                    <td id="Timeline_Photo">
                        
                    </td>
                </tr>
            </table>
        </div>

        <div class="buttons">
            <button class="btn btn-outline-success" type="submit">登録</button>
            <a class="btn btn-outline-primary" href="{% url 'travel_planning:mylist' %}">キャンセル</a>
        </div>
    </form>
</div>

<script src="{% static 'js/sharePlan.js' %}"></script>
<script src="{% static 'js/memoSpaceSmall.js' %}"></script>

{% endblock %}

travel_planning/templates/shiozaki/share_results.html
{% extends "../base.html" %}

{% load i18n %}

{% block head_title %}結果{% endblock %}

{% block content %}

{% load static %}

<h2>登録が完了しました。</h2>

<a class="btn btn-outline-primary" href="{% url 'travel_planning:list' %}">OK</a>

{% endblock %}

travel_planning/templates/shiozaki/share_success.html
{% extends "../base.html" %}

{% load i18n %}

{% block head_title %}登録完了{% endblock %}

{% block content %}

{% load static %}
<style>
    h2 {
        text-align: center;
        padding: 14px 0;
    }

    a {
        width: 100px;
        margin: 0 auto;
        text-align: center;
        padding-bottom: 100px;
    }

    #main {
        text-align: center;
    }
</style>

<h2>登録が完了しました。</h2>

<a class="btn btn-outline-primary" href="{% url 'travel_planning:mylist' %}">OK</a>

<br>

{% endblock %}