config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.contrib.staticfiles.urls import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('travel_planning.urls')),
    path('accounts/', include('allauth.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

travel_planning/urls.py
from django.urls import path
from . import views

app_name = 'travel_planning'
urlpatterns = [
    # path('',views.MapView.as_view(), name='map'),
    path('', views.IndexView.as_view(), name='index'),
    path('automap/',views.AutomapView.as_view(), name='automap'),
    path('automap/<int:pk>/',views.MyPlanUpdateView.as_view(), name='plan-update'),
    # path('test/', views.TestView.as_view(), name='test')
    path('share/detail/<int:pk>/', views.SharePlanView.as_view(), name='share'),
    
    path('share/plan-list', views.PlanListView.as_view(), name='list'),
    path('share/success', views.ShareSuccessView.as_view(), name='success'),
    path('share/canceled', views.ShareCanceledView.as_view(), name='canceled'),
    
    path('my-plan-list', views.MyPlanListView.as_view(), name='mylist'),
    path('plan-detail/<int:pk>', views.MyPlanDetailView.as_view(), name='mydetail'),
    path('plan-delete/<int:pk>', views.MyPlanDeleteView.as_view(), name='mydelete'),

    #コピーのURL
    path('map_copy/<int:pk>/',views.PlanCopyView.as_view(), name='plan-copy'),
]

travel_planning/models.py
from django.db import models
from accounts.models import CustomUser

import os
import time
from datetime import datetime

#旅行計画モデル
class Plan(models.Model):
    user = models.ForeignKey(CustomUser, verbose_name='ユーザー', on_delete=models.PROTECT)
    prefectural_names = models.TextField(verbose_name='県名') #例：'千葉県,東京都'
    photo = models.ImageField(verbose_name='メイン画像', blank=True, null=True)
    detail = models.TextField(verbose_name='詳細')
    plan = models.TextField(verbose_name='旅行計画') #例：'牛久大仏,ChIJ4-9ANlRuImARS4u9SEpdN8I,986,60;浄土宗 佛法山 東漸寺,ChIJeakrKlKbGGAR3PKsg0N6oFQ,1110,60;'、splitで展開
    sub_details = models.TextField(verbose_name='サブ詳細一覧') #例：'詳細1;詳細2;'
    created_at = models.DateTimeField(verbose_name='作成日時', max_length=10, auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name='更新日時', max_length=10, auto_now=True, blank=True, null=True)
    is_deleted = models.BooleanField(verbose_name='削除フラグ', default=False)
    is_action = models.BooleanField(verbose_name='公開フラグ', default=False)

    class Meta:
        verbose_name_plural = 'Plan'
    
    def __str__(self):
        string = self.plan.split(",")
        return string[0] #例：20代男性
    
    def ago(self):
        dt_now = time.time() #現在時刻
        dt_updated = self.updated_at.timestamp() #更新日の取得
        
        diff = dt_now - dt_updated #差分
        
        d = datetime.utcfromtimestamp(diff)
        
        if d.year - 1970:
            return str(d.year - 1970) + "年前"
        elif d.month - 1:
            return str(d.month - 1) + "ヵ月前"
        elif d.day - 1:
            return str(d.day) + "日前"
        elif d.hour:
            return str(d.hour) + "時間前"
        elif d.minute:
            return str(d.minute) + "分前"
        else:
            return "数秒前"

#いいねモデル（未使用）
class Like(models.Model):
    user = models.ForeignKey(CustomUser, verbose_name='ユーザー', on_delete=models.PROTECT)
    plan = models.ForeignKey(Plan, verbose_name='旅行計画', on_delete=models.PROTECT)

    class Meta:
        verbose_name_plural = 'Like'
    
    def __str__(self):
        return self.user.username #仮です！

travel_planning/forms.py
from django import forms
from .models import Plan

class MyPlanCreateForm(forms.ModelForm):
    class Meta:
        model = Plan
        fields = ('prefectural_names','plan')
        def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)


class MyPlanUpdateForm(forms.ModelForm):
    class Meta:
        model = Plan
        fields = ('prefectural_names','plan')
        def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)

travel_planning/views.py
from django.shortcuts import render
from django.views import generic
from django.contrib import messages

from .forms import MyPlanUpdateForm, MyPlanCreateForm
from django.urls import reverse_lazy

from .models import *
from django.contrib.auth.mixins import LoginRequiredMixin

from config import settings
import os

# Create your views here.
class IndexView(generic.TemplateView):
    template_name = "index.html"
    
class AutomapView(generic.CreateView):
    template_name = 'auto.html'
    model = Plan
    form_class = MyPlanCreateForm

    def post(self, request, *args, **kwargs):
        try:
            plan = Plan(user=request.user, prefectural_names=request.POST["prefectural_names"], plan=request.POST["plan"])
            plan.save()

            messages.success(request, '計画を保存しました。')
        except:
            messages.error(request, 'エラーが起きたようです。')
        return render(request, 'auto.html')


class TestView(generic.TemplateView):
    template_name = "test.html"

class PlanListView(generic.ListView):
    model = Plan
    template_name = "plan_list.html"

    def get_queryset(self):
        plans = Plan.objects.filter(prefectural_names__contains='北海道').filter(is_action=True).order_by('-created_at')
        return plans

    def post(self, request, *args, **kwargs):
        plans = Plan.objects.filter(prefectural_names__contains=request.POST['prefs']).filter(is_action=True).order_by('-created_at')
        context = {
            'prefsValue' : request.POST['prefs'],
            'plan_list' : plans
        }
        return render(request, 'plan_list.html', context)

class SharePlanView(LoginRequiredMixin, generic.DetailView):
    # 問題点：自分が他人の計画を投稿できてしまう
    model = Plan
    template_name = "shiozaki/share_plan.html"

    def __init__(self, *args, **kwargs):
        print(args)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        plan = Plan.objects.get(id=self.kwargs['pk']).plan
        subD = Plan.objects.get(id=self.kwargs['pk']).sub_details
        detailList = subD.split(';')

        perPlace = plan.split(';')
        planList = []

        for i in range(len(perPlace)):
            place = perPlace[i].split(",")
            place.append(detailList[i] if i < len(detailList) else '')
            planList.append(place)
        
        context = {
            'object' : Plan.objects.get(id=self.kwargs['pk']),
            'planList' : planList,
        }
        return context

class ShareSuccessView(generic.TemplateView):
    def post(self, request, *args, **kwargs):
        context = {
            'mainPhoto': request.FILES['メイン画像'],
            'mainDescription': request.POST['詳細'],
            'subDescription': request.POST.getlist('サブ詳細'),
        }
        subDes = ''
        for index in range(len(context['subDescription'])):
            subDes += context['subDescription'][index]
            if index != (len(context['subDescription'])-1):
                subDes += ';'

        os.chdir(os.getcwd() + settings.MEDIA_URL)

        file_obj = request.FILES.get("メイン画像")
        f1=open(file_obj.name,"wb")

        for i in file_obj.chunks():
            f1.write(i)

        f1.close()

        os.chdir('..')

        Plan.objects.filter(id=request.POST['ID']).update(
            photo=context['mainPhoto'],
            detail=context['mainDescription'], 
            sub_details=subDes, is_action=True
        )
        return render(request, 'shiozaki/share_success.html')

class ShareCanceledView(generic.TemplateView):
    #共有取り消しビュー（塩﨑）
    def post(self, request, *args, **kwargs):
        Plan.objects.filter(id=request.POST['ID']).update(
            is_action=False
        )
        return render(request, 'shiozaki/share_canceled.html')


class MyPlanListView(generic.ListView):
    model = Plan
    template_name = "my_plan_list.html"

    def get_queryset(self):
        plans = Plan.objects.filter(user=self.request.user).order_by('-created_at')
        return plans
    
    def post(self, request, *args, **kwargs):
        try:
            plan = Plan(user=request.user, prefectural_names=request.POST["prefectural_names"], plan=request.POST["plan"])
            plan.save()

            messages.success(request, '計画を保存しました。')
        except:
            messages.error(request, 'エラーが起きたようです。')

        return render(request, 'my_plan_list.html')

class MyPlanDetailView(generic.DetailView):
    model = Plan
    template_name = "shiozaki/plan_detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        
        user = Plan.objects.get(id=self.kwargs['pk']).user
        plan = Plan.objects.get(id=self.kwargs['pk']).plan
        subD = Plan.objects.get(id=self.kwargs['pk']).sub_details
        detailList = subD.split(';')

        perPlace = plan.split(';')
        planList = []

        for i in range(len(perPlace)):
            place = perPlace[i].split(",")
            place.append(detailList[i] if i < len(detailList) else '')
            planList.append(place)
        
        context = {
            'object' : Plan.objects.get(id=self.kwargs['pk']),
            'planOwner' : user,
            'planList' : planList
        }
        return context

class MyPlanUpdateView(LoginRequiredMixin, generic.UpdateView):
    #問題点：他人の計画を編集できてしまう
    """
    注意！
    仕様のため、保存ボタンを押さないとエラーが起きません！
    """
    model = Plan
    template_name = 'auto.html'
    form_class = MyPlanUpdateForm

    def get_success_url(self):
        return reverse_lazy('travel_planning:mydetail', kwargs={'pk': self.kwargs['pk']})
    def form_valid(self, form):
        if Plan.objects.get(id=self.kwargs['pk']).user == self.request.user:
            messages.success(self.request, '更新しました。')
            return super().form_valid(form)
        else:
            messages.error(self.request, "更新に失敗しました。")
            return super().form_invalid(form)

    def form_invalid(self, form):
        messages.error(self.request, "更新に失敗しました。")
        return super().form_invalid(form)
#追加コード（塩崎）
class MyPlanDeleteView(LoginRequiredMixin, generic.DeleteView):
    #削除ビュー
    model = Plan
    template_name = 'shiozaki/share_delete.html'
    success_url = reverse_lazy('travel_planning:mylist')

    def delete(self, request, *args, **kwargs):
        #削除フラグ使う・・・？
        messages.success(self.request, "計画を削除しました。")
        return super().delete(request, *args, **kwargs)

class PlanCopyView(LoginRequiredMixin, generic.CreateView):
    #コピーに使うビュー
    #問題点：自分の計画をコピーできてしまう（多分）
    model = Plan
    template_name = 'auto.html'
    form_class = MyPlanCreateForm

    def get_context_data(self, **kwargs):
        try:
            if Plan.objects.get(id=self.kwargs['pk']).user == self.request.user:
                messages.error(self.request, "エラーが起こりました。")

                return {}
            else:
                #URLにあるPKから計画一覧を取得
                plan = Plan.objects.get(id=self.kwargs['pk']).plan

                context = {
                    'copiedPlan' : plan
                }
                return context
        except self.model.DoesNotExist:
            messages.error(self.request, "エラーが起こりました。")
            return {}

travel_planning/templates/base copy.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <title>{% block head_title %}{% endblock %}</title>
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" referrerpolicy="no-referrer">
    </script>
    <link rel="stylesheet" type="text/css" href="{% static 'css/commonStyle.css' %}">
    {% block new_style %}{% endblock %}

</head>

<body>
    <nav id="main_nav" class="navbar navbar-expand-lg navbar-light bg-white shadow">
        <div class="container d-flex justify-content-between align-items-center">
            <a class="navbar-brand h1" href="{% url 'travel_planning:index' %}">
                TriPlan
            </a>
            <button class="navbar-toggler border-0" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbar-toggler-success" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="align-self-center collapse navbar-collapse flex-fill bg-white d-lg-flex justify-content-lg-between"
                id="navbar-toggler-success">
                <div class="flex-fill mx-xl-5 mb-2">
                    <ul class="nav navbar-nav d-flex justify-content-between mx-xl-5 text-dark">
                        <li class="nav-item">
                            <a class="nav-link   rounded-pill px-3" href="{% url 'travel_planning:automap' %}">旅行計画</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link   rounded-pill px-3" href="{% url 'travel_planning:list' %}">旅行検索</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link   rounded-pill px-3" href="">散策モード</a>
                        </li>
                </div>
                <div class="align-self-center d-flex">
                    <div class="hidden fixed nav-item top-0 right-0 px-6 sm:block">
                        {% if user.is_authenticated %}
                        <div class="dropdown">
                            <div class="d-flex align-items-center hidden-arrow" href="#"
                                id="navbarDropdownMenuAvatar btnOpenMenu" role="button" data-toggle="dropdown"
                                aria-expanded="false">
                                <i class="far fa-user-circle fa-2x btn"></i>
                            </div>
                            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownMenuAvatar">
                                <li>
                                    <a class="dropdown-item" href="{% url 'travel_planning:mylist' %}">保存プラン一覧</a>
                                </li>
                                <li>
                                    <a class="dropdown-item" href="{% url 'account_logout' %}">ログアウト</a>
                                </li>
                            </ul>
                        </div>
                        {% else %}
                        <a href="{% url 'account_login' %}" class="nav-link   rounded-pill px-3 mb-2"
                            style="float: left">ログイン</a>
                        <a href="{% url 'account_signup' %}" class="nav-link   rounded-pill px-3 mb-2"
                            style="float: left">会員登録</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </nav>

    {% if messages %}
    <br>
    <div class="container">
        <div class="row">
            <div class="my-div-style w-100">
                <ul class="messages" style="list-style: none;">
                    {% for message in messages %}
                    <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
    {% endif %}

    {% block content %}
    {% endblock %}

    <!-- <script>
        $(".openbtn4").click(function () {
            $(this).toggleClass('active');
            ToggleMemo();
        });
    </script> -->
    <!-- bootstrap js -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous">
        </script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
        </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous">
        </script>
    <!-- <script
        src="https://maps.googleapis.com/maps/api/js?language=ja&key=AIzaSyDeL7_U--qzVwi963J1elplZfLTCIsduZQ&libraries=places&callback=initMap">
        </script> -->
    <!-- <script src="https://maps.googleapis.com/maps/api/js?language=ja&key=AIzaSyAIvDT6aSB8xK3ASJLRpicJ_SZV8KngMLM&libraries=places&callback=initMap"></script> -->
</body>

</html>

travel_planning/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ja">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>{% block head_title %}{% endblock %}</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{% static 'assets/img/favicon.png' %}" rel="icon">
  <link href="{% static 'assets/img/apple-touch-icon.png' %}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'assets/vendor/aos/aos.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{% static 'assets/css/style.css' %}" rel="stylesheet" type="text/css">

  <!-- =======================================================
  * Template Name: Maxim - v4.7.0
  * Template URL: https://bootstrapmade.com/maxim-free-onepage-bootstrap-theme/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
  <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" referrerpolicy="no-referrer">
  </script>
  {% block new_style %}{% endblock %}
</head>

<body>

  <!-- ======= Header ======= -->
  <header id="header" class="fixed-top d-flex align-items-center">
    <div class="container d-flex justify-content-between">

      <div class="logo">
        <h1><a href="{% url 'travel_planning:index' %}">Travel to Freedom</a></h1>
        <!-- Uncomment below if you prefer to use an image logo -->
        <!-- <a href="index.html"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->
      </div>

      <nav id="navbar" class="navbar">
        <ul>
          <!-- <li><a class="nav-link scrollto active" href="#hero">Home</a></li>
          <li><a class="nav-link scrollto" href="#about">About</a></li>
          <li><a class="nav-link scrollto" href="#services">Services</a></li>
          <li><a class="nav-link scrollto " href="#portfolio">Portfolio</a></li>
          <li><a class="nav-link scrollto" href="#team">Team</a></li>
          <li class="dropdown"><a href="#"><span>Drop Down</span> <i class="bi bi-chevron-down"></i></a>
            <ul>
              <li><a href="#">Drop Down 1</a></li>
              <li class="dropdown"><a href="#"><span>Deep Drop Down</span> <i class="bi bi-chevron-right"></i></a>
                <ul>
                  <li><a href="#">Deep Drop Down 1</a></li>
                  <li><a href="#">Deep Drop Down 2</a></li>
                  <li><a href="#">Deep Drop Down 3</a></li>
                  <li><a href="#">Deep Drop Down 4</a></li>
                  <li><a href="#">Deep Drop Down 5</a></li>
                </ul>
              </li>
              <li><a href="#">Drop Down 2</a></li>
              <li><a href="#">Drop Down 3</a></li>
              <li><a href="#">Drop Down 4</a></li>
            </ul>
          </li>
          <li><a class="nav-link scrollto" href="#contact">Contact</a></li> -->
          <li><a class="nav-link" href="{% url 'travel_planning:automap' %}">旅行計画</a></li>
          <li><a class="nav-link" href="{% url 'travel_planning:list' %}">旅行検索</a></li>
          <li><a class="nav-link" href="#">散策モード</a></li>
          {% if user.is_authenticated %}
          <li class="dropdown"><a href="#"><span>{{ user }}<i class="far fa-user-circle"></i></span> <i class="bi bi-chevron-down"></i></a>
            <ul>
              <li><a href="{% url 'travel_planning:mylist' %}">保存プラン一覧</a></li>
              <li><a href="{% url 'account_logout' %}">ログアウト</a></li>
            </ul>
          </li>
          {% else %}
          <li><a class="nav-link" href="{% url 'account_login' %}">ログイン</a></li>
          <li><a class="nav-link" href="{% url 'account_signup' %}">会員登録</a></li>
          {% endif %}
        </ul>
        <i class="bi bi-list mobile-nav-toggle"></i>
      </nav><!-- .navbar -->

    </div>
  </header><!-- End Header -->

  <main id="main">
    {% if messages %}
    <br>
    <div class="container">
      <div class="row">
        <div class="my-div-style w-100">
          <ul class="messages" style="list-style: none;">
            {% for message in messages %}
            <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
            {% endfor %}
          </ul>
        </div>
      </div>
    </div>
    {% endif %}
    
    {% block content %}
    {% endblock %}
  </main><!-- End #main -->

  <!-- ======= Footer ======= -->
  <footer id="footer">
    <!-- <div class="footer-top">
      <div class="container">
        <div class="row">

          <div class="col-lg-3 col-md-6">
            <div class="footer-info">
              <h3>Maxim</h3>
              <p>
                A108 Adam Street <br>
                NY 535022, USA<br><br>
                <strong>Phone:</strong> +1 5589 55488 55<br>
                <strong>Email:</strong> info@example.com<br>
              </p>
              <div class="social-links mt-3">
                <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>
                <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
                <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
                <a href="#" class="google-plus"><i class="bx bxl-skype"></i></a>
                <a href="#" class="linkedin"><i class="bx bxl-linkedin"></i></a>
              </div>
            </div>
          </div>

          <div class="col-lg-2 col-md-6 footer-links">
            <h4>Useful Links</h4>
            <ul>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Home</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">About us</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Services</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Terms of service</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Privacy policy</a></li>
            </ul>
          </div>

          <div class="col-lg-3 col-md-6 footer-links">
            <h4>Our Services</h4>
            <ul>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Web Design</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Web Development</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Product Management</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Marketing</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Graphic Design</a></li>
            </ul>
          </div>

          <div class="col-lg-4 col-md-6 footer-newsletter">
            <h4>Our Newsletter</h4>
            <p>Tamen quem nulla quae legam multos aute sint culpa legam noster magna</p>
            <form action="" method="post">
              <input type="email" name="email"><input type="submit" value="Subscribe">
            </form>

          </div>

        </div>
      </div>
    </div> -->

    <div class="container">
      <div class="copyright">
        &copy; 2022 <strong><span><a href="https://school.o-hara.ac.jp/kashiwa/">TravelToFreedom.com</a></span></strong>
      </div>
    </div>
  </footer><!-- End Footer -->

  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src="{% static 'assets/vendor/aos/aos.js' %}"></script>
  <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'assets/vendor/glightbox/js/glightbox.min.js' %}"></script>
  <script src="{% static 'assets/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
  <script src="{% static 'assets/vendor/swiper/swiper-bundle.min.js' %}"></script>
  <script src="{% static 'assets/vendor/php-email-form/validate.js' %}"></script>

  <!-- Template Main JS File -->
  <script src="{% static 'assets/js/main.js' %}"></script>

</body>

</html>

travel_planning/templates/my_plan_list.html
{% extends "base.html" %}

{% load static %}

{% block head_title %}保存プラン一覧{% endblock %}


{% block content %}
<style>
    /* プランカードのスタイル */
    .card-horizontal {
        display: flex;
        flex: 1 1 auto;
    }
</style>
<main class="main mt-3">
    <div class="m-2">
        <div class="container">
            <h1 class="text-center p-2 mb-5 mt-5 h2">保存プラン一覧</h1>
            <div class="row">

                {% for plan in plan_list %}
                <div class="card mr-auto al-auto mb-4">
                    <div class="card-horizontal">
                        {% if plan.photo %}
                        <div class="img-square-wrapper">
                            <img style="width: 300px; height: 180px;" src="{{ plan.photo.url }}" alt="Card image cap">
                        </div>
                        {% endif %}
                        <div class="card-body">
                            <h4 class="card-title">{{ plan }}</h4>
                            <p class="card-text">{{ plan.detail }}</p>
                        </div>
                    </div>

                    <div class="card-footer">
                        <small class="text-muted">{{ plan.ago }}</small>
                        <small class="text-muted">{{ plan.prefecture_name }}</small>

                        <div class="btn-group ml-5">
                            <a href="{% url 'travel_planning:plan-update' plan.pk %}" class="mr-1">
                                <button type="button" class="btn btn-sm btn-outline-secondary">詳細</button>
                            </a>
                            {% if plan.is_action %}
                            <a href="{% url 'travel_planning:mydetail' plan.pk %}" class="mr-1">
                                <button type="button" class="btn btn-sm btn-outline-secondary">閲覧</button>
                            </a>
                            {% else %}
                            <a href="{% url 'travel_planning:share' plan.pk %}">
                                <button type="button" class="btn btn-sm btn-outline-secondary">投稿</button>
                            </a>
                            {% endif %}
                            <a href="{% url 'travel_planning:mydelete' plan.pk %}" class="mr-1">
                                <button type="button" class="btn btn-sm btn-outline-secondary">削除</button>
                            </a>
                        </div>
                    </div>

                </div>
                {% empty %}
                保存している計画はありません。
                {% endfor %}

            </div>
        </div>
</main>

<script>
    const card_title = document.getElementsByClassName('card-title');

    function omittedContent(string) {
        // 定数で宣言
        const MAX_LENGTH = 12;

        // もしstringの文字数がMAX_LENGTH（今回は14）より大きかったら末尾に...を付け足して返す。
        if (string.length > MAX_LENGTH) {

            // substr(何文字目からスタートするか, 最大値);
            return string.substr(0, MAX_LENGTH) + '...';
        }
        //　文字数がオーバーしていなければそのまま返す
        return string;
    }

    for (var i = 0; i < card_title.length; i++) {
        card_title[i].innerText = `${omittedContent(card_title[i].innerText)}`;
    }
</script>

{% endblock %}